// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmxbuvdvhsgauigareok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFteGJ1dmR2aHNnYXVpZ2FyZW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzMTc3MTEsImV4cCI6MjA4NDg5MzcxMX0.x7a488HJxd-iL9aOjpvP8x0InNmKXztgJHhiVJdljPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});